cloud:
  aws:
    credentials:
      access-key: AKIA2UC27PZGWZNOXFH5
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: awsbucketmnc


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080